config/routes.rb
Rails.application.routes.draw do
  resources :line_items

  resources :carts

  resources :orders

  resources :interns

  resources :job_posters

  resources :free_agents

  resources :investes

  resources :investors

  resources :roles

  resources :salesmen

  resources :likes

  resources :products do
  get :autocomplete, :on => :collection
  end

  resources :categories   
  devise_for :users ,:controllers => { :registrations => "registrations" }

  get "welcome/show_dealer", :as => :dealer
  get "welcome/show_account", :as => :account, :via => [:get, :post]
  get "welcome/analytics", :as => :analytics
  get "welcome/terms_candition", :as => :terms_candition
  match "products/:id/all_likes"=> 'products#all_likes', :as => :all_likes, :via => [:get, :post]
  match "products/:id/unlike_likes"=> 'products#unlike_likes', :as => :unlike_likes, :via => [:get, :post]
  

  root :to => 'welcome#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  validates_uniqueness_of :name
  validates_format_of :name, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/
  has_many :products
end

app/models/country_list.rb
class CountryList < ActiveRecord::Base
end

app/models/free_agent.rb
class FreeAgent < ActiveRecord::Base
validates :Headline, :Details, :presence => { :message => "is required" }
validates_uniqueness_of :Headline
end

app/models/intern.rb
class Intern < ActiveRecord::Base
  validates :Headline, :Details, :presence => { :message => "is required" }
  validates_uniqueness_of :Headline
end

app/models/investe.rb
class Investe < ActiveRecord::Base
validates :Company, :Opportunity_Headline, :Description, :presence => { :message => "is required" }
validates_uniqueness_of :Company
end

app/models/investor.rb
class Investor < ActiveRecord::Base
validates :Company, :Equity_Investment, :Revenue, :EBITDA, :presence => { :message => "is required" }
validates_uniqueness_of :Company
end

app/models/job_poster.rb
class JobPoster < ActiveRecord::Base
validates :Headline, :Details, :presence => { :message => "is required" }
validates_uniqueness_of :Headline
end

app/models/like.rb
class Like < ActiveRecord::Base
belongs_to :product
  belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :photo, :styles => { :original => "300x300>", :thumb => "100x100>" },
                  :url  => "/assets/products/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
  #validates_numericality_of :price, presence: true
  validates :price, presence: true, numericality: true
  validates :quantity, presence: true, numericality: true
  validates_format_of :name, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
  validates :name, presence: true
  validates_uniqueness_of :name
  belongs_to :category
  belongs_to :user
  has_many :likes
  has_many :users, through: :likes
  has_many :line_items
  has_many :orders, :through => :line_items
  
  def self.search(search)  
    if search  
      where('name LIKE ?', "%#{search}%")  
    else  
      scoped  
    end  
  end  

  def to_param
    "#{name}"
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/salesman.rb
class Salesman < ActiveRecord::Base
belongs_to :user
validates :name, :address, :presence => { :message => "is required" }
validates_uniqueness_of :name
end

app/models/session.rb
class Session < ActiveRecord::Base
  def self.sweep(time = 1.hour)
    if time.is_a?(String)
      time = time.split.inject { |count, unit| count.to_i.send(unit) }
    end
    delete_all "updated_at < '#{time.ago.to_s(:db)}'"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :resume
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable
  has_many :products, through: :likes
  has_many :likes, dependent: :destroy
  has_many :salesmen
  belongs_to :country_list
  # specify that the resume is a paperclip file attachment
  validates_presence_of :first_name, :message => "is required" 
  validates :last_name, :presence => { :message => "is required" }
  has_attached_file :resume, :message => "is required"
  validates_attachment_presence :resume
  #validates_acceptance_of :terms_accepted, :message => "is required"
  validates_attachment_content_type :resume, :content_type =>['application/pdf'],
  :path => ":rails_root/public/assets/resumes/:id/:style/:basename.:extension",
  :url => ":rails_root/public/assets/resumes/:id/:style/:basename.:extension"

  before_create do
    self.last_name = first_name.capitalize if last_name.blank?
  end
  # def timeout_in
  #   2.minute 
  # end
end

app/controllers/job_posters_controller.rb
class JobPostersController < ApplicationController
  before_action :set_job_poster, only: [:show, :edit, :update, :destroy]
  before_action :require_login
  respond_to :html

  def index
    @job_posters = JobPoster.all
    respond_with(@job_posters)
  end

  def show
    respond_with(@job_poster)
  end

  def new
    if current_user.admin? && user_signed_in?
      @job_poster = JobPoster.new
      respond_with(@job_poster)
    else 
      render :text => "<h2>Sorry,You are not authorised to create the <b>JobPoster</b> at this time!</h2>", :status => '404', :layout => true   ## show message for unauthorised
    end
  end

  def edit
  end

  def create
    @job_poster = JobPoster.new(job_poster_params)
    if @job_poster.valid?
      @job_poster.save
      flash[:success] = "JobPoster created!"
      redirect_to root_url
    else 
      flash[:error] = @job_poster.errors
      render :template => "job_posters/new"
    end
  end

  def update
    @job_poster.update(job_poster_params)
    respond_with(@job_poster)
  end

  def destroy
    @job_poster.destroy
    respond_with(@job_poster)
  end

  private
    def require_login
      unless user_signed_in?
        flash[:error] = "You must be logged in to access this section"
        redirect_to new_user_session_path # halts request cycle
      end
    end


  private
    def set_job_poster
      @job_poster = JobPoster.find(params[:id])
    end

    def job_poster_params
      params.require(:job_poster).permit(:Headline, :Details)
    end
end

app/helpers/interns_helper.rb
module InternsHelper
end

app/helpers/investes_helper.rb
module InvestesHelper
end

app/helpers/investors_helper.rb
module InvestorsHelper
end

app/helpers/job_posters_helper.rb
module JobPostersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/salesmen_helper.rb
module SalesmenHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/job_posters/_form.html.erb
<%= form_for(@job_poster) do |f| %>
  <% if @job_poster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_poster.errors.count, "error") %> prohibited this job_poster from being saved:</h2>

      <ul>
      <% @job_poster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Headline %>
    <%= f.text_field :Headline %>
  </div>
  <div class="field">
    <%= f.label :Details %>
    <%= f.text_area :Details %>
  </div>
  <div class="actions">
  <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/job_posters/edit.html.erb
<h1>Editing job_poster</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_poster %> |
<%= link_to 'Back', job_posters_path %>

app/views/job_posters/index.html.erb
<h1>Listing job_posters</h1>

<table>
  <thead>
    <tr>
      <th>Headline</th>
      <th>Details</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @job_posters.each do |job_poster| %>
      <tr>
        <td><%= job_poster.Headline %></td>
        <td><%= job_poster.Details %></td>
        <td><%= link_to 'Show', job_poster %></td>
        <td><%= link_to 'Edit', edit_job_poster_path(job_poster) %></td>
        <td><%= link_to 'Destroy', job_poster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job poster', new_job_poster_path %>

app/views/job_posters/new.html.erb
<h1>New Job Poster</h1>

<%= render 'form' %>

<%#= link_to 'Back', job_posters_path %>

app/views/job_posters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Headline:</strong>
  <%= @job_poster.Headline %>
</p>

<p>
  <strong>Details:</strong>
  <%= @job_poster.Details %>
</p>

<%= link_to 'Edit', edit_job_poster_path(@job_poster) %> |
<%= link_to 'Back', job_posters_path %>