config/routes.rb
Rails.application.routes.draw do
  resources :line_items

  resources :carts

  resources :orders

  resources :interns

  resources :job_posters

  resources :free_agents

  resources :investes

  resources :investors

  resources :roles

  resources :salesmen

  resources :likes

  resources :products do
  get :autocomplete, :on => :collection
  end

  resources :categories   
  devise_for :users ,:controllers => { :registrations => "registrations" }

  get "welcome/show_dealer", :as => :dealer
  get "welcome/show_account", :as => :account, :via => [:get, :post]
  get "welcome/analytics", :as => :analytics
  get "welcome/terms_candition", :as => :terms_candition
  match "products/:id/all_likes"=> 'products#all_likes', :as => :all_likes, :via => [:get, :post]
  match "products/:id/unlike_likes"=> 'products#unlike_likes', :as => :unlike_likes, :via => [:get, :post]
  

  root :to => 'welcome#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  validates_uniqueness_of :name
  validates_format_of :name, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/
  has_many :products
end

app/models/country_list.rb
class CountryList < ActiveRecord::Base
end

app/models/free_agent.rb
class FreeAgent < ActiveRecord::Base
validates :Headline, :Details, :presence => { :message => "is required" }
validates_uniqueness_of :Headline
end

app/models/intern.rb
class Intern < ActiveRecord::Base
  validates :Headline, :Details, :presence => { :message => "is required" }
  validates_uniqueness_of :Headline
end

app/models/investe.rb
class Investe < ActiveRecord::Base
validates :Company, :Opportunity_Headline, :Description, :presence => { :message => "is required" }
validates_uniqueness_of :Company
end

app/models/investor.rb
class Investor < ActiveRecord::Base
validates :Company, :Equity_Investment, :Revenue, :EBITDA, :presence => { :message => "is required" }
validates_uniqueness_of :Company
end

app/models/job_poster.rb
class JobPoster < ActiveRecord::Base
validates :Headline, :Details, :presence => { :message => "is required" }
validates_uniqueness_of :Headline
end

app/models/like.rb
class Like < ActiveRecord::Base
belongs_to :product
  belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :photo, :styles => { :original => "300x300>", :thumb => "100x100>" },
                  :url  => "/assets/products/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
  #validates_numericality_of :price, presence: true
  validates :price, presence: true, numericality: true
  validates :quantity, presence: true, numericality: true
  validates_format_of :name, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
  validates :name, presence: true
  validates_uniqueness_of :name
  belongs_to :category
  belongs_to :user
  has_many :likes
  has_many :users, through: :likes
  has_many :line_items
  has_many :orders, :through => :line_items
  
  def self.search(search)  
    if search  
      where('name LIKE ?', "%#{search}%")  
    else  
      scoped  
    end  
  end  

  def to_param
    "#{name}"
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/salesman.rb
class Salesman < ActiveRecord::Base
belongs_to :user
validates :name, :address, :presence => { :message => "is required" }
validates_uniqueness_of :name
end

app/models/session.rb
class Session < ActiveRecord::Base
  def self.sweep(time = 1.hour)
    if time.is_a?(String)
      time = time.split.inject { |count, unit| count.to_i.send(unit) }
    end
    delete_all "updated_at < '#{time.ago.to_s(:db)}'"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :resume
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable
  has_many :products, through: :likes
  has_many :likes, dependent: :destroy
  has_many :salesmen
  belongs_to :country_list
  # specify that the resume is a paperclip file attachment
  validates_presence_of :first_name, :message => "is required" 
  validates :last_name, :presence => { :message => "is required" }
  has_attached_file :resume, :message => "is required"
  validates_attachment_presence :resume
  #validates_acceptance_of :terms_accepted, :message => "is required"
  validates_attachment_content_type :resume, :content_type =>['application/pdf'],
  :path => ":rails_root/public/assets/resumes/:id/:style/:basename.:extension",
  :url => ":rails_root/public/assets/resumes/:id/:style/:basename.:extension"

  before_create do
    self.last_name = first_name.capitalize if last_name.blank?
  end
  # def timeout_in
  #   2.minute 
  # end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :require_login
  respond_to :html
  def index
    if params[:search]
      @products = Product.search(params[:search]).paginate(:per_page => 4, :page => params[:page])
    else 
      @products = Product.paginate(page: params[:page], per_page: 3) 
      @like_ids = Like.all.collect(&:product_id)
      @product_ids = Product.all.collect(&:id)
      respond_with(@products)
    end
  end


  def show
    respond_with(@product)
  end

  def new
    if current_user.admin? && user_signed_in?
      @product = Product.new
      respond_with(@product)
    else 
      render :text => "<h2>Sorry,You are not authorised to create the <b>Product</b> at this time!</h2>", :status => '404', :layout => true  ## show message for unauthorised
    end
  end

  def edit
  end

  def create
      @product = current_user.products.build(product_params)
      @product.save
      respond_with(@product)
  end

  def update
    @product.update(product_params)
    respond_with(@product)
  end

  def destroy
    @product.destroy
    respond_with(@product)
  end

  def block_deal
    @block_deal = Product.find(params[:id])
    @block_deal.update_attributes(:deal => 'false')
    respond_with(@block_deal)
  end

  def all_likes
    @deal = Product.find(params[:id])
    if !Like.exists?(product_id: params[:id])
     @test = Like.create(:user_id => current_user.id, :product_id => params[:id])
    respond_with(@test)
    end
  end

  def unlike_likes
    @deal = Product.find(params[:id])
     @destroy_like = Like.where(:product_id => params[:id].to_i).destroy_all
    respond_with(@destroy_like)
 end

  def autocomplete
    @products = Product.find(:all, :conditions => ['name LIKE ?', "%#{params[:search]}%"])
    @hash = []
    @products.each do |pro|
      @hash << {"label" => pro.name, "id" => pro.id}
    end
      render :json => @hash
  end

  private
    def require_login
      unless user_signed_in?
        flash[:error] = "You must be logged in to access this section"
        redirect_to new_user_session_path # halts request cycle
      end
    end

  private
    def set_product
      @product = Product.find_by_name(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :category_id, :user_id, :price, :quantity, :deal, :category_name, :photo)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/interns_helper.rb
module InternsHelper
end

app/helpers/investes_helper.rb
module InvestesHelper
end

app/helpers/investors_helper.rb
module InvestorsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/salesmen_helper.rb
module SalesmenHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
<div class="control-group">
  <% if @product.errors.any? %>
    <div id="error_explanation" style="width:200px";"color:#0000FF">
      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_name , :class => 'control-label' %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price , :class => 'control-label' %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :quantity , :class => 'control-label' %>
    <%= f.text_field :quantity %>
  </div>
   <div class="field">
    <%= f.label :choose_category , :class => 'control-label' %>
  <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :image , :class => 'control-label' %>
  <%= f.file_field :photo %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
     <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:quantity) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th> 
      <th></th>
      <% if user_signed_in? && current_user.dealer? %>
      <th><%= model_class.human_attribute_name(:deal) %></th> 
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= link_to image_tag(product.photo.url(:original)), product_path(product) %></td>
        <td><%= number_to_currency(product.price, :unit => "$") %></td>
        <td><%= product.quantity %></td>
        <td><%= product.created_at.strftime("%B %e, %Y") %></td>
        <td>
        <% if user_signed_in? && current_user.admin? %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
          <% end %>
        </td>
        <td>
        <% if user_signed_in? && current_user.dealer? %>
          <% if product.id != product.likes.collect(&:product_id).last.to_i %>
          <div id ="like_btn"><%= link_to "Deal", all_likes_path(product.id) , method: :post, remote: true, :class => 'btn btn-primary' %></div>
          <% else %>
            <div id ="unlike_btn"><%= link_to "Not Deal", unlike_likes_path(product.id) , method: :post, remote: true , :class => 'btn btn-primary' %></div>
          <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @products %>
<script>
$(document).ready(function(){
  $("#like_btn").click(function(){
 window.location.reload();
  });
  $("#unlike_btn").click(function(){
 window.location.reload();
  });
});
</script>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<title><%= @product.name %></title>


<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= image_tag @product.photo.url(:original) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:quantity) %>:</strong></dt>
  <dd><%= @product.quantity %></dd>
  <dd>
    <dd>
      <a href="http://twitter.com/share" class="twitter-share-button">Tweet</a> 
<script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>
<script src="/assets/javascripts/widgets.js"></script>
    </dd>

    <dd><div class="fb-like" data-href="https://mysterious-wildwood-8925.herokuapp.com/products/" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div></dd>

  <dd><div class="fb-comments" data-href="https://mysterious-wildwood-8925.herokuapp.com/products/" data-numposts="5" data-colorscheme="light"></div></dd>
</dl>

<% if user_signed_in? && current_user.admin? %>
<%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

<% end %>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=196293653897861&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=196293653897861&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<script>
    $(".fb-like").attr("data-href", window.location.href);
</script>
<script>
    $(".fb-comments").attr("data-url", window.location.href);
</script>
<script>
    $(".twitter-share-button").attr("data-href", window.location.href);
</script>

<%#= tweet_button(:via => "Sandeepchourey", :url => "https://mysterious-wildwood-8925.herokuapp.com/products", :text => @product.name ) %>